sudo: false

language: go

services:
  - docker

go:
- "1.14.2"

script:
  - make lint
  - make test-version
  - make test-unit
  - make test-e2e-all

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - make
