apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../high-availability-1.21+
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: metrics-server
    namespace: kube-system
  path: patch.yaml
images:
  - name: registry.k8s.io/metrics-server/metrics-server
    newName: gcr.io/k8s-staging-metrics-server/metrics-server
    newTag: master
