{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "system:%s" (include "metrics-server.fullname" .) }}
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ template "metrics-server.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metrics-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
