apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: gcr.io/k8s-staging-metrics-server/metrics-server
  newName: registry.k8s.io/metrics-server/metrics-server
  newTag: v0.6.0
